### PR TITLE
Fix : Page Number Bar

### LINKED ISSUE #366: Page number bar
**Describe the bug - Décrivez le bogue**
The page number bar on the first question page of the AIA displays page 1 of 9 when it should be page 1 of 13.

Screen Shot 2020-09-21 at 10 16 10 AM

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Go to the first question page of the AIA

### PR DESCRIPTION
**Pull request by SalimErradi**
Fixes #366

### CODE REVIEW

File: src/views/Home.vue [hunk 1]
```diff
@@ -70,6 +70,21 @@ export default class Home extends Vue {
       this.$router.push("Results");
     });
 
+    this.Survey.onAfterRenderPage.add(result => {
+      var progressBar = document.getElementsByClassName("progress-bar")[0];
+      //Make sure that the current page is 0 and the progress bar is defined and displayed on the screen
+      if (result.currentPageNo == 0 && progressBar != undefined) {
+        progressBar.innerHTML = "Page 1 of 13";
```
Comment (MrDeshaies) [inline src/views/Home.vue:77]: This text needs to be locale dependent... "Page 1 de 13" en francais

File: src/views/Home.vue [hunk 2]
```diff
@@ -70,6 +70,21 @@ export default class Home extends Vue {
...
+      }
+      //Increment the current page by one
+      else {
+        if (progressBar.innerHTML != undefined) {
+          progressBar.innerHTML =
+            "Page " + (result.currentPageNo + 1) + " of 13";
```
Comment (MrDeshaies) [inline src/views/Home.vue:83]: "Page X de 13" en francais

**Review by MrDeshaies — APPROVED** [review]
all good now
