### PR TITLE
Ben changes

### LINKED ISSUE #263: Fairness implementation questions missing result text
Selecting "yes" to the Fairness mitigation measures during the Implementation stage results in a lot of keys being displayed on the results page, as opposed to the text for these elements. It works correctly for the Design stage.  Design/Implementation is a question on page 1.

image

### LINKED ISSUE #264: PDF Generation error with process optimization
If you select "Process optimization & workflow automation: Analyzing large data sets to identify and anomalies, cluster patterns, predict outcomes or ways to optimize; and automate specific workflows" on pp 5 (About the system), the PDF fails to generate on the results screen, with the error below. I suspect the very suspicious ampersand.

`pdfmake.min.js:37 Uncaught Unrecognized document structure: {"ul":"","style":["html-ul"]}`

### LINKED ISSUE #265: Exporting to PDF Issue
**Describe the bug - Décrivez le bogue**
We have completed an AIA and are trying to export it to PDF.  There is an issue on page 5 of the survey.  When "Process optimization & workflow automation: Analyzing large data sets to identify and anomalies, cluster patterns, predict outcomes or ways to optimize; and automate specific workflows" is checked off it breaks the export function for PDF at the end of the survey.

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Go to page 5 of the survey
2. Click on "Process optimization & workflow automation: Analyzing large data sets to identify and anomalies, cluster patterns, predict outcomes or ways to optimize; and automate specific workflows" 
3.  Finish the survey
4. Export to PDF.

AIA Issue Capture

**Expected behavior**
The export to PDF should work at the end of the survey.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Edge

### PR DESCRIPTION
**Pull request by MrDeshaies**
Fixes #263 
Fixes #264 
Fixes #265

### CODE REVIEW

File: src/components/MultiChoiceResult.vue [hunk 1]
```diff
@@ -4,9 +4,13 @@
       <strong v-if="locale == undefined">{{ data.title }}</strong>
       <strong v-if="locale !== undefined">{{ data.titleData[locale] }}</strong>
       <br />
-      <ul v-for="(str, index) in data.value" :key="index">
-        <li>{{ getItemLabel(str, index) }}</li>
-      </ul>
+      <div v-for="(str, index) in data.value" :key="index">
```
Comment (MrDeshaies) [inline src/components/MultiChoiceResult.vue:7]: Aligns this component with MultiChoiceValueResult. Fixes the bug, and gives a consistent look and code.

File: src/plugins/en.json [hunk 2]
```diff
@@ -78,23 +78,23 @@
...
-    "proceduralFairnessImplementation11": "There is a process in place to grant, monitor, and revoke access permission to the system.",
-    "proceduralFairnessImplementation12": "There is a mechanism to capture feedback by users of the systems.",
-    "proceduralFairnessImplementation13": "There is a recourse process in place for clients that wish to challenge the decision.",
-    "proceduralFairnessImplementation14": "The system enables human override of system decisions.",
-    "proceduralFairnessImplementation15": "There is a process in place to log instances when overrides were performed.",
-    "proceduralFairnessImplementation16": "The system's audit trail includes change control processes to record modifications to the system's operation or performance.",
-    "proceduralFairnessImplementation17": "A concept case has been prepared and approved by the Government of Canada Enterprise Architecture Review Board.",
+    "fairnessImplementation1": "The audit trail clearly identifies the authority or delegated authority as identified in legislation.",
```
Comment (MrDeshaies) [inline src/plugins/en.json:81]: Fix the key names, and align with survey-en-fr.json, where the order was different.

File: src/survey-enfr.json [hunk 3]
```diff
@@ -1104,7 +1104,7 @@
                                 {
                                     "value": "item5",
                                     "text": {
-                                        "default": "Process optimization & workflow automation: Analyzing large data sets to identify and anomalies, cluster patterns, predict outcomes or ways to optimize; and automate specific workflows",
```
Comment (MrDeshaies) [inline src/survey-enfr.json:1107]: The only ampersand in the entire file. Caused one problem (fixed through code), but using "and" seems safer and may prevent future issues.
